llm:
  provider: ollama
  config:
    model: 'mistral'
    temperature: 1
    top_p: 1
    stream: true
    base_url: http://localhost:11434
    
embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/paraphrase-multilingual-mpnet-base-v2'