name: Build and Run Docker Container

on:
  push:
    branches:
      - main
      - homologacao

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --build-arg BRANCH=${{ github.ref }} -t apibeta .

      - name: Run Docker container
        run: docker run -e BRANCH=${{ github.ref }} -p 8000:8000 apibeta
